version: "3.8"

services:
    postgres_99tech:
        image: "postgres:latest"
        container_name: postgres_99tech
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_pw
            POSTGRES_DB: postgres_db
        volumes:
            - ./db-data/postgres/:/var/lib/postgresql/data
        networks:
            - problem5-networks

    # server_nodejs:
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./server
    #     container_name: server_nodejs
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         - "postgres_test"
    #     networks:
    #         - problem5-networks

networks:
    problem5-networks:
        driver: bridge
